import House from "phosphor-react-native/src/icons/House";
import Tag from "phosphor-react-native/src/icons/Tag";
import SingOut from "phosphor-react-native/src/icons/SignOut";
import Eye from "phosphor-react-native/src/icons/Eye";
import EyeClosed from "phosphor-react-native/src/icons/EyeClosed";
import User from "phosphor-react-native/src/icons/User";
import PencilLine from "phosphor-react-native/src/icons/PencilSimpleLine";
import Plus from "phosphor-react-native/src/icons/Plus";
import ArrowRight from "phosphor-react-native/src/icons/ArrowRight";
import ArrowLeft from "phosphor-react-native/src/icons/ArrowLeft";
import MagnifyingGlassMinus from "phosphor-react-native/src/icons/MagnifyingGlass";
import Sliders from "phosphor-react-native/src/icons/Sliders";
import X from "phosphor-react-native/src/icons/X";
import BarCode from "phosphor-react-native/src/icons/Barcode";
import CreditCard from "phosphor-react-native/src/icons/CreditCard";
import QrCode from "phosphor-react-native/src/icons/QrCode";
import Money from "phosphor-react-native/src/icons/Money";
import Bank from "phosphor-react-native/src/icons/Bank";
import TrashSimple from "phosphor-react-native/src/icons/TrashSimple";
import Power from "phosphor-react-native/src/icons/Power";
import Replay from "phosphor-react-native/src/icons/ArrowsCounterClockwise";


export const HouseIcon = House;
export const TagIcon = Tag;
export const SignOutIcon = SingOut;
export const EyeIcon = Eye;
export const EyeClosedIcon = EyeClosed;
export const UserIcon = User;
export const PencilLineIcon = PencilLine;
export const PlusIcon = Plus;
export const ArrowRightIcon = ArrowRight;
export const ArrowLeftIcon = ArrowLeft;
export const MagnifyingGlassMinusIcon = MagnifyingGlassMinus;
export const SlidersIcon = Sliders;
export const XIcon = X;
export const BarCodeIcon = BarCode;
export const CreditCardIcon = CreditCard;
export const QrCodeIcon = QrCode;
export const MoneyIcon = Money;
export const BankIcon = Bank;
export const TrashSimpleIcon = TrashSimple;
export const PowerIcon = Power;
export const ReplayIcon = Replay;
